projet-synthese/WikiWikiWeb/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf import settings
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    # weditor
    url(r'^$', 'weditor.views.index', name='index'),
    url(r'^accueil$', 'weditor.views.home', name='home'),
    url(r'^recherche$', 'weditor.views.search', name='search'),
    url(r'^cree$', 'weditor.views.create', name='create'),
    url(r'^integre/(\w+)$', 'weditor.views.link', name='link'),
    url(r'^modifie/(\d+)$', 'weditor.views.edit', name='edit'),
    url(r'^supprime/(\d+)$', 'weditor.views.delete', name='delete'),
    url(r'^recharge/(\d+)/(\d+)$', 'weditor.views.review', name='review'),
    url(r'^profil$', 'weditor.views.profile', name='profile'),
    url(r'^configure$', 'weditor.views.settings', name='settings'),
    url(r'^inscrit$', 'weditor.views.subscribe', name='subscribe'),
    url(r'^connecte$', 'weditor.views.login', name='login'),
    url(r'^deconnecte$', 'weditor.views.logout', name='logout'),

    # other apps
    url(r'^captcha/', include('captcha.urls')),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^wxcvbn/', include(admin.site.urls)),

    # Static and media files
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
)

projet-synthese/WikiWikiWeb/weditor/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core import validators
from django.contrib.auth.models import User

name_validator = validators.RegexValidator(r'^[0-9a-zA-Z- ]*$', "Seul les caractères alphanumériques, '-' et des espaces sont admis")


class Wiki(models.Model):
    display_name = models.CharField("Nom d'affichage", max_length=30, unique=True, validators=[name_validator,])
    api_url = models.URLField("URL de l'API")
    date_created = models.DateTimeField("Ajouté le", auto_now_add=True, editable=False)
    date_updated = models.DateTimeField("Modifié le", auto_now=True, editable=False)

    def __unicode__(self):
        return self.display_name

    class Meta:
        verbose_name = u"Wiki"
        verbose_name_plural = u"Wiki"
        ordering = ('display_name',)


class Settings(models.Model):
    VERSION_LIMITS = zip(range(2,11), range(2,11))

    version_limit = models.PositiveIntegerField("Limite du nombre de version", default=10, choices=VERSION_LIMITS)
    default_wiki = models.ForeignKey(Wiki, verbose_name="Wiki utilisé par défaut", blank=True, null=True)
    user = models.OneToOneField(User, verbose_name="Utilisateur", editable=False)

    def __unicode__(self):
        return "Configuration de " + self.user.username

    class Meta:
        verbose_name = u"Configuration"
        verbose_name_plural = u"Configurations"
        ordering = ('user',)


class Article(models.Model):
    OK = 'OK'
    NEW = 'NEW'
    DRAFT = 'DRAFT'
    CONFLICT = 'CONFLICT'

    STATES = (
        (OK, u"OK"),
        (NEW, u"Nouveau"),
        (DRAFT, u"Brouillon"),
        (CONFLICT, u'Conflit'),
    )

    title = models.CharField("Titre", max_length=30, validators=[name_validator,])
    state = models.CharField("État", max_length=10, choices=STATES, default=OK)
    url = models.URLField("URL de l'article", blank=True, editable=False)
    date_created = models.DateTimeField("Ajouté le", auto_now_add=True, editable=False)
    date_updated = models.DateTimeField("Modifié le", auto_now=True, editable=False)
    date_refreshed = models.DateTimeField("Dernière MAJ", null=True, editable=False)
    date_published = models.DateTimeField("Dernière publication", null=True, editable=False)
    user = models.ForeignKey(User, verbose_name="Utilisateur", editable=False)
    wiki = models.ForeignKey(Wiki, verbose_name="Wiki")

    def link(self):
        if self.url:
            return u"""<a href="%s" title="Cliquez pour voir l'article sur le Wiki" target="_blank">%s</a>""" % (self.url, self.title)
        else:
            return self.title
    link.allow_tags = True
    link.short_description = "Lien vers l'article"

    def clean_old_versions(self):
        limit = self.user.settings.version_limit
        versions_to_delete =  Version.objects.filter(article=self.id).order_by('-date_created')[limit:]

        for v in versions_to_delete:
            v.delete()

    @staticmethod
    def exists(title, user):
        return Article.objects.filter(title=title, user=user).exists()

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = u"Article"
        verbose_name_plural = u"Articles"
        ordering = ('wiki', 'user', 'state', '-date_updated',)


class Version(models.Model):
    CREATION = 'CRE'
    RESOLUTION = 'RES'
    MODIFICATION = 'MOD'
    IMPORT = 'IMP'
    DOWNLOAD = 'DOW'
    REVIEW = 'REV'
    ORIGINS = (
        (CREATION, u"Création"),
        (RESOLUTION, u'Résolution'),
        (MODIFICATION, u'Modification'),
        (IMPORT, u"Import"),
        (DOWNLOAD, u"Récupération"),
        (REVIEW, u"Reprise"),
    )

    text = models.CharField("Texte", blank=True, max_length=512)
    origin = models.CharField("Origine", max_length=3, choices=ORIGINS)
    counter = models.PositiveIntegerField("Numéro de version", default=1)
    date_created = models.DateTimeField("Ajouté le", auto_now_add=True, editable=False)
    article = models.ForeignKey(Article, verbose_name="Article", editable=False)

    def __unicode__(self):
        return str(self.id)

    class Meta:
        verbose_name = u"Version"
        verbose_name_plural = u"Versions"
        ordering = ('article__user__username', '-date_created',)

projet-synthese/WikiWikiWeb/weditor/forms.py
# -*- coding: utf-8 -*-

from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, UserCreationForm
from captcha.fields import CaptchaField
from models import Settings, Article
from django import forms


class AuthForm(AuthenticationForm):
    username = forms.CharField(label="Nom utilisateur", max_length=30,
                               widget=forms.TextInput(attrs={'placeholder': "nom d'utilisateur", 'data-mini': 'true', 'required': 'true'}))
    password = forms.CharField(label="Mot de passe", min_length=8,
                               widget=forms.PasswordInput(attrs={'placeholder': "mot de passe", 'data-mini': 'true', 'required': 'true'}))

    def check_for_test_cookie(self):
        pass


class AuthFormWithCaptcha(AuthForm):
    captcha = CaptchaField(label="Test de Turing")


class ProfileForm(PasswordChangeForm):
    new_password1 = forms.CharField(label="Nouveau mot de passe", min_length=8, widget=forms.PasswordInput)
    new_password2 = forms.CharField(label="Confirmation du nouveau mot de passe", min_length=8, widget=forms.PasswordInput)


class SubscribeForm(UserCreationForm):
    password1 = forms.CharField(label="Mot de passe", min_length=8, widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirmation du mot de passe", min_length=8, widget=forms.PasswordInput)
    captcha = CaptchaField(label="Test de Turing")


class SettingsForm(forms.ModelForm):

    class Meta:
        model = Settings


class CreateArticleForm(forms.ModelForm):
    text = forms.CharField(label="Contenu de l'article", widget=forms.Textarea)

    class Meta:
        model = Article
        exclude = ['state',]


class EditArticleForm(forms.ModelForm):
    text = forms.CharField(label="Contenu de l'article", widget=forms.Textarea)

    class Meta:
        model = Article
        exclude = ['title', 'state', 'wiki']

projet-synthese/WikiWikiWeb/weditor/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render_to_response, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.template.context import RequestContext
from django.contrib import messages
from django.http import Http404
from api.mediawiki.errors import APIException
from addons import raise404_if_different
import logging

logger = logging.getLogger('weditor')

def index(request):
    from forms import AuthForm

    # redirect to home if already log in
    if request.user.is_authenticated():
        return redirect('home')

    return render_to_response('pages/index.html', context_instance=RequestContext(request))


@login_required
def home(request):
    from django.conf import settings
    from models import Wiki, Article
    from addons import can_create_article

    wikis = Wiki.objects.all()
    articles = Article.objects.filter(user=request.user)

    return render_to_response('pages/home.html',
                              {'wikis': wikis, 'articles': articles,
                               'can_create_article': can_create_article(request),
                               'limit_create': settings.ARTICLES_PER_USER},
                              context_instance=RequestContext(request))


@login_required
def search(request):
    from django.conf import settings
    from api.mediawiki.requests import search
    from models import Article, Wiki
    from addons import can_create_article

    if not can_create_article(request):
        messages.warning(request, "Vous ne pouvez pas gérer plus de %d articles sur WikiWikiWeb!" % settings.ARTICLES_PER_USER)
        return redirect('home')

    if request.method == 'GET':
        get = request.GET.dict()

        if 'q' in get.keys() and len(get['q']):
            get['q'] = get['q'][0:50]

            if not 'wiki' in get:
                messages.warning(request, "Le wiki n'a pas été précisé dans les critères de recherche. Veuillez recommencer.")
                return redirect('home')

            wiki = get_object_or_404(Wiki, pk=get['wiki'])

            try:
                results = search(wiki.api_url, get['q'])
            except APIException as e:
                messages.warning(request, "Erreur de communication avec l'API. L'administrateur a été averti.")
                logger.error('%s (action=search)' % e)
                return redirect('home')

            cached_request = get
            cached_request['wiki'] = wiki
            cached_request['results'] = results
            request.session[settings.SEARCH_SESSION] = cached_request
        else:
            if not settings.SEARCH_SESSION in request.session:
                messages.warning(request, "Vous n'avez lancé aucune recherche")
                return redirect('home')

    query = request.session[settings.SEARCH_SESSION]

    return render_to_response('pages/search.html', {'query': query}, context_instance=RequestContext(request))


@login_required
def link(request, id):
    from django.conf import settings
    from models import Article, Version
    from api.mediawiki.requests import get_article_content
    from datetime import datetime

    if settings.SEARCH_SESSION not in request.session.keys():
        messages.warning(request, "Vous n'avez lancé aucune recherche")
        return redirect('home')

    if Article.objects.filter(user=request.user).count() >= settings.ARTICLES_PER_USER:
        messages.warning(request, "Vous ne pouvez pas gérer plus de %d articles sur WikiWikiWeb!" % settings.ARTICLES_PER_USER)
        return redirect('home')

    try:
        id = int(id)
        wiki = request.session[settings.SEARCH_SESSION]['wiki']
        wiki_article = request.session[settings.SEARCH_SESSION]['results'][id]
    except (ValueError, IndexError):
        messages.warning(request, "Impossible de retrouver l'article parmis vos résultats de recherche")
        return redirect('search')

    if Article.exists(wiki_article['title'], request.user):
        messages.warning(request, "L'article a déjà été crée ou importé")
        return redirect('search')

    try:
        content = get_article_content(wiki.api_url, wiki_article['title'])
    except APIException as e:
        messages.warning(request, "Erreur de communication avec l'API. L'administrateur a été averti.")
        logger.error('%s (action=link)' % e)
        return redirect('search')

    if len(content) > 512:
        messages.warning(request, "L'article fait plus de 512 caractères (%d), il ne peut pas être importé." % len(content))
        return redirect('search')

    article = Article.objects.create(
        title=wiki_article['title'],
        state=Article.OK,
        url=wiki_article['url'],
        user=request.user,
        wiki=wiki,
        date_refreshed=datetime.now()
    )
    Version.objects.create(
        origin=Version.IMPORT,
        text=content,
        article=article
    )

    messages.success(request, "L'article a bien été ajouté à votre interface")

    return redirect('home')


@login_required
def create(request):
    from django.conf import settings
    from forms import CreateArticleForm
    from models import Article, Version
    from addons import can_create_article

    # limit the number of article
    if not can_create_article(request):
        messages.warning(request, "Vous ne pouvez pas gérer plus de %d articles sur WikiWikiWeb !" % settings.ARTICLES_PER_USER)
        return redirect('home')

    if request.method == 'POST':
        create_form = CreateArticleForm(request.POST)
        create_form.instance.user = request.user
        create_form.instance.state = Article.NEW

        if create_form.is_valid():
            if Article.exists(create_form.instance.title, request.user):
                messages.warning(request, "Un article du même nom a déjà été crée/importé dans votre interface")
            else:
                if len(create_form.cleaned_data['text']) > 512:
                    messages.warning(request, "L'article fait plus de 512 caractères (%d), il ne peut pas être crée." % len(create_form.cleaned_data['text']))
                else:
                    article = create_form.save()
                    Version.objects.create(origin=Version.CREATION, text=create_form.cleaned_data['text'], article=article)
                    return redirect('home')
    else:
        create_form = CreateArticleForm()
        create_form.fields['wiki'].initial = request.user.settings.default_wiki

    return render_to_response('pages/create.html', {'create_form': create_form},
                              context_instance=RequestContext(request))


@login_required
def edit(request, article_id):
    from forms import EditArticleForm
    from models import Article, Version
    from datetime import datetime

    if request.method == 'POST' and 'publish' in request.POST.keys():
        return publish(request, article_id)
    elif request.method == 'POST' and 'refresh' in request.POST.keys():
        return refresh(request, article_id)
    elif request.method == 'POST' and 'save' not in request.POST.keys():
        messages.warning(request, u"Action de modification inconnue")
        return redirect('edit', article_id)

    article = get_object_or_404(Article, pk=article_id)
    raise404_if_different(article.user, request.user)
    versions = Version.objects.filter(article=article).all()

    if len(versions) < 1:
        messages.warning(request, u"L'article \"%s\" n'est pas versionné." % (article.title,))
        logger.error("Article non versionné: %s" % article_id)
        return redirect('home')

    last_version = versions[0]
    history = versions[1:]

    if request.method == 'POST':
        edit_form = EditArticleForm(request.POST, instance=article)
        origin = Version.MODIFICATION
        if edit_form.instance.state == Article.CONFLICT:
            edit_form.instance.date_refreshed = datetime.now()
            origin = Version.RESOLUTION
        if article.state != Article.NEW:
            edit_form.instance.state = Article.DRAFT

        if edit_form.is_valid():
            if len(edit_form.cleaned_data['text']) > 512:
                messages.warning(request, "L'article fait plus de 512 caractères (%d), il ne peut pas être modifié." % len(edit_form.cleaned_data['text']))
            else:
                article = edit_form.save()
                version = Version.objects.create(
                    counter=last_version.counter+1,
                    origin=origin,
                    text=edit_form.cleaned_data['text'],
                    article=article
                )
                article.clean_old_versions()
                messages.success(request, u"L'article \"%s\" a bien été modifié ! (#%s)" % (article.title, version.counter))

                return redirect('edit', article_id)
    else:
        edit_form = EditArticleForm(instance=article, initial={'text': last_version.text,})

    # retrieve the last Wiki article on conflict
    last_wiki_version = None
    if article.state == Article.CONFLICT:
        from api.mediawiki.requests import get_article_content
        try:
            last_wiki_version = get_article_content(article.wiki.api_url, article.title)
        except APIException as e:
            messages.warning(request, "Erreur de communication avec l'API. L'administrateur a été averti.")
            logger.error('%s (action=edit)' % e)
            return redirect('edit', article_id)

    return render_to_response('pages/edit.html', {'edit_form': edit_form,
                                                  'article': article,
                                                  'last_wiki_version': last_wiki_version,
                                                  'history': history,},
                              context_instance=RequestContext(request))


@login_required
def review(request, article_id, version_id):
    from models import Article, Version
    from datetime import datetime

projet-synthese/WikiWikiWeb/weditor/templates/pages/create.html
{% extends 'layout/main.html' %}

{% block head_extras %}
<script src="{{ STATIC_URL }}js/ckeditor/ckeditor.js"></script>
<script src="{{ STATIC_URL }}js/ckeditor-config.js"></script>

<script>
    $(document).ready(function() {
        CKEDITOR.replace('id_text', article_config);
    });
</script>
{% endblock %}

{% block content %}
<div id="content" class="align_center">
    <h3>Création d'un nouvel article</h3>
    <br />

    {% if messages %}
    {% for message in messages %}
    <br />
    <p class="message-line {{ message.tags }} important">
        {{ message }}
    </p>
    <br />
    {% endfor %}
    {% endif %}

    <form action="{% url 'create' %}" method="post" id="create_form">
        {% csrf_token %}

        <div class="ui-grid-a">
            <div class="ui-block-a">
                <label for="id_title">{{ create_form.title.label }}:</label>
                {{ create_form.title }}
                {{ create_form.title.errors }}
            </div>


            <div class="ui-block-b">
                <label for="id_wiki">{{ create_form.wiki.label }}:</label>
                {{ create_form.wiki }}
                {{ create_form.wiki.errors }}
            </div>
        </div>

        <br />

        <div>
            {{ create_form.text }}
            {{ create_form.text.errors }}
        </div>

        <br />

        <div>
            <input type="submit" value="Enregistrer mes modifications" data-mini="true" data-iconpos="top" data-icon="check" data-inline="true" />
        </div>
    </form>

    <div class="clear"></div>
</div>
{% endblock %}

projet-synthese/WikiWikiWeb/weditor/templates/pages/edit.html
{% extends 'layout/main.html' %}

{% block head_extras %}
<script src="{{ STATIC_URL }}js/ckeditor/ckeditor.js"></script>
<script src="{{ STATIC_URL }}js/ckeditor-config.js"></script>

<script>
    $(document).ready(function() {
        // initialize CKEditor
        CKEDITOR.replace('id_text', article_config);
        {% for version in history %}
        CKEDITOR.replace('version-text-{{ version.id }}', version_config);
        {% endfor %}

        {% if last_wiki_version %}
        CKEDITOR.replace('wiki-version-text', version_config);
        {% endif %}

        // go at the bottom of the page
        $("#goto-history").click(function (e) {
            $("html, body").animate({ scrollTop: $(document).height() }, "slow");
        });

        // switch between history versions
        $('.see-version').click(function (e) {
            var version_id = $(this).attr('data-idref');
            $('.version-container').hide('slow');
            $('#version-container-' + version_id).show('slow');
            $('.version-list tr').removeClass('selected');
            $(this).parent().parent().addClass('selected');
        });
    });
</script>
{% endblock %}

{% block content %}
<div id="content" class="align_center">
    <h3>Édition de l'article: {{ article.title }}{% if last_wiki_version %} <span class="red">(conflit)</span>{% endif %}</h3>

    {% if messages %}
     {% for message in messages %}
    <br />
    <p class="message-line {{ message.tags }} important">
        {{ message }}
    </p>
    <br />
    {% endfor %}
    {% endif %}

    <br />

    {% if last_wiki_version %}
    <p class="important">
        Pour résoudre le conflit, vous pouvez modifier votre travail et l'enregistrer ou perdre votre travail en récupérant la version Wiki.
    </p>

    <br />

    <h4 class="orange">Version du Wiki</h4>
    <div id="wiki-version-container"">
        <textarea id="wiki-version-text">
            {{ last_wiki_version }}
        </textarea>
    </div>
    <br />
    {% endif %}

    <div class="right">
        Pour voir l'historique, <a href="#" id="goto-history">cliquez ici</a>
    </div>

    <br />

    <form action="{% url 'edit' article.id %}" method="post" id="edit_form">
        {% csrf_token %}

        <div>
            {{ edit_form.text }}
            {{ edit_form.text.errors }}
        </div>

        <br />

        <div class="ui-grid-b">
            <div class="ui-block-a align_left">
                {% if article.state == article.DRAFT or article.state == article.CONFLICT %}
                <input type="submit" name="refresh" value="Récupérer la dernière version" data-icon="update" data-iconpos="top" data-mini="true" data-inline="true" onclick="javascript:return confirm('Cette action va remplacer cette version par la dernière version du Wiki (vos modifications seront perdues).\nÊtes vous sûr ?');" />
                {% endif %}
            </div>
            <div class="ui-block-b align_center">
                <input type="submit" name="save" value="Enregistrer mes modifications" data-mini="true" data-iconpos="top" data-icon="check" data-inline="true" />
            </div>
            <div class="ui-block-c align_right">
                {% if article.state == article.DRAFT or article.state == article.NEW %}
                <input type="submit" name="publish" value="Publier l'article sur le Wiki" data-icon="publish" data-iconpos="top" data-mini="true" data-inline="true" onclick="javascript:return confirm('Avant d\'envoyer votre article, pensez à enregistrer vos modifications.\nContinuer ?');"/>
                </a>
                {% endif %}
            </div>
        </div>
    </form>

    <div class="clear"></div>
    <br /><hr /><br />

    <div class="history">
        <h4>Historique de vos modifications</h4>

        <br />

        <div class="ui-grid-a">
            <div class="ui-block-a">
                <table class="version-list">
                {% for version in history %}
                    <tr>
                        <td class="version-id important">
                            #{{ version.counter }}
                        </td>
                        <td class="infos">
                            {{ version.get_origin_display }} du {{ version.date_created }}
                        </td>
                        <td class="actions">
                            <a href="#" class="see-version" data-idref="{{ version.id }}" data-role="button" data-icon="see" data-iconpos="notext" data-mini="true" data-inline="true" title="Voir le texte"></a>
                            <a href="{% url 'review' article.id version.id %}" class="reload-version" data-idref="{{ version.id }}" data-role="button" data-icon="refresh" data-iconpos="notext" data-mini="true" data-inline="true" title="Retourner à la version de cette article" onclick="javascript:return confirm('Cette action va créer une nouvelle version basée celle que vous voulez recharger.\nÊtes-vous sûr de vouloir continuer ?');"></a>
                        </td>
                    </tr>
                {% endfor %}
                </table>
            </div>

            <div class="ui-block-b">
                {% for version in history %}
                <div class="version-container" id="version-container-{{ version.id }}">
                    <textarea class="version-text" id="version-text-{{ version.id }}">
                        {{ version.text }}
                    </textarea>
                </div>
                {% endfor %}
            </div>
        </div>

        <div class="clear"></div><br />

        <p class="note" id="history-goto">
            Pour modifier le nombre de version que vous voulez conserver, rendez-vous sur <a href="{% url 'settings' %}">la page de configuration</a>
        </p>
    </div>

    <div class="clear"></div>
</div>
{% endblock %}

projet-synthese/WikiWikiWeb/weditor/templates/pages/index.html
{% extends 'layout/main.html' %}

{% block content %}
<div id="content" class="ui-grid-a">
    <div id="promo" class="ui-block-a align_center">
        <img src="{{ STATIC_URL }}images/wikipedia.png" alt="Logo Wikipédia" height="300" />

        <br /><br />

        <p>
            <strong>WikiWikiWeb</strong> vous offre une interface simple et réactive, <br/>pour éditer les pages de n'importe quel wiki.
            <br /><br />
            Rejoignez une communauté vibrante avec un outil fait pour vous !
        </p>
    </div>

    <div id="subscribe" class="ui-block-b align_center">
        <a href="{% url 'subscribe' %}" class="old-school">Inscription old-school »</a>

        <br /><br />

        <p class="or">
            OU
        </p>

        <br /><br />

        <a href="{% url 'login' %}" class="login">Connexion old-school »</a>
        <a href="/login/yahoo/" class="yahoo">Connexion avec Yahoo »</a>
        <a href="/login/google" class="google">Connexion avec Google »</a>
    </div>
</div>
{% endblock %}

projet-synthese/WikiWikiWeb/weditor/templates/pages/login.html
{% extends 'layout/main.html' %}

{% block identity %}{% endblock %}

{% block content %}
<div id="content" class="align_center">
    <h3 class="big dark-green">Connectez-vous à WikiWikiWeb !</h3>

    <br />

    <form action="{% url 'login' %}" id="login_form" method="post" class="limit center">
        {% csrf_token %}

        <div>
            <label for="id_username">{{ auth_form.username.label }}:</label>
            {{ auth_form.username }}
            {{ auth_form.username.errors }}
        </div>

        <br />

        <div>
            <label for="id_password">{{ auth_form.password.label }}:</label>
            {{ auth_form.password }}
            {{ auth_form.password.errors }}
        </div>

        {% if auth_form.captcha %}
            <br />

            <div>
                <div class="ui-grid-a">
                    <div class="ui-block-a">
                        <label for="id_captcha" class="important">Êtes vous un humain ?</label>
                        <br /><br />
                        Pour le vérifiez,
                        <br />
                        saisissez le mot suivant:
                    </div>
                    <div class="ui-block-b">
                        {{ auth_form.captcha }}
                    </div>
                    {{ auth_form.captcha.errors }}
                    {{ auth_form.captcha.help_text }}
                </div>
            </div>
        {% endif %}

        {% if auth_form.non_field_errors %}
            <br />
            {{ auth_form.non_field_errors }}
            <br />
        {% else %}
            <br /><br />
        {% endif %}

        <input type="submit" name="submit" value="Me Connecter" />
    </form>
</div>
{% endblock %}

projet-synthese/WikiWikiWeb/weditor/templates/pages/profile.html
{% extends 'layout/main.html' %}

{% block content %}
<div id="content" class="align_center">
    {% if messages %}
        {% for message in messages %}
        <p class="dark-green important big">
            {{ message }}
        </p>

        <br />

        <div class="ui-grid-a">
            <a href="{% url 'home' %}" class="ui-block-a" data-role="button" data-icon="home" data-iconpos="top">Retour à la page d'accueil</a>
            <a href="{% url 'profile' %}" class="ui-block-b" data-role="button" data-icon="user" data-iconpos="top">Modifier de nouveau mon profil</a>
        </div>
        {% endfor %}
    {% else %}
        <h3>Gestion de mon profil</h3>
        <br />

        <form action="{% url 'profile' %}" method="post" id="profile_form" class="center limit">
            {% csrf_token %}

            <div>
                <label for="id_old_password">{{ profile_form.old_password.label }}:</label>
                {{ profile_form.old_password }}
                {{ profile_form.old_password.errors }}
            </div>

            <br />

            <div>
                <label for="id_new_password1">{{ profile_form.new_password1.label }}:</label>
                {{ profile_form.new_password1 }}
                {{ profile_form.new_password1.errors }}
            </div>

            <br />

            <div>
                <label for="id_new_password2">{{ profile_form.new_password2.label }}:</label>
                {{ profile_form.new_password2 }}
                {{ profile_form.new_password2.errors }}
            </div>

            {% if profile_form.non_field_errors %}
                <br />
                {{ profile_form.non_field_errors }}
                <br />
            {% else %}
                <br /><br />
            {% endif %}

            <br />

            <input type="submit" value="Mettre à jour mes informations" />
        </form>
    {% endif %}
</div>
{% endblock %}

projet-synthese/WikiWikiWeb/weditor/templates/pages/settings.html
{% extends 'layout/main.html' %}

{% block content %}
<div id="content" class="align_center">
    {% if messages %}
        {% for message in messages %}
        <p class="dark-green important big">
            {{ message }}
        </p>

        <br />

        <div class="ui-grid-a">
            <a href="{% url 'home' %}" class="ui-block-a" data-role="button" data-icon="home" data-iconpos="top">Retour à la page d'accueil</a>
            <a href="{% url 'settings' %}" class="ui-block-b" data-role="button" data-icon="gear" data-iconpos="top">Modifier de nouveau mes préférences</a>
        </div>
        {% endfor %}
    {% else %}
        <h3>Gestion de mes préférences</h3>
        <br />

        <form action="{% url 'settings' %}" method="post" id="profile_form" class="center limit">
            {% csrf_token %}

            {{ settings_form }}

            <div>
                <label for="id_new_password1">{{ settings_form.new_password1.label }}:</label>
                {{ settings_form.new_password1 }}
                {{ settings_form.new_password1.errors }}
            </div>

            {% if settings_form.non_field_errors %}
                <br />
                {{ settings_form.non_field_errors }}
                <br />
            {% else %}
                <br /><br />
            {% endif %}

            <br />

            <input type="submit" value="Mettre à jour mes préférences" />
        </form>
    {% endif %}
</div>
{% endblock %}